### ISSUE TITLE
[Feat] Partial constraint application by Sig type

### ISSUE THREAD

**Issue by sidprasad** [sidprasad/copeanddrag#20]
Augment field constraints (aka, refine them) to only apply to *some* sig types?

For instance:

```
constraints:
    - orientation:
        field: left
        directions: [below, left]
```

could be augmented further to only apply when things are of type SubNode->SubNode2

```
constraints:
    - orientation:
        field: left
        directions: [below, left]
        ofType : [SubNode, NubNode2]

```

where the default is `univ -> univ` (or the field's decl type) (aka everything in the field)
